--- # My First YAML Playbook
- hosts: all
  user: ansible
  sudo: yes                       # yes or no
  connection: ssh                 # ssh or paramico
  gather_facts: yes               # yes or no
  tasks:
   - name: install httpd on CentOS7
     action: yum name=httpd state=installed
     async: 30
     poll: 1 
     notify: Start Apache
  handlers:
   - name: Start Apache
     action: service name=httpd state=started
