--- # My First YAML Playbook
- hosts: all
  user: ansible
  sudo: yes                       # yes or no
  connection: ssh                 # ssh or paramico
  gather_facts: yes               # yes or no
  tasks:
   - name: install httpd on Debian
     command: apt-get -y install apache2
     when: ansible_os_family == "Debian"
   - name: install httpd on Redhat
     command: yum -y install httpd
     when: ansible_os_family == "RedHat"
   - name: running loop on this task
     command: echo {{ item }}
     with_items: [ 0,2,4,6,8,10 ]
     when: item > 5
