--- # My First YAML Playbook
- hosts: all 
  user: ansible
  sudo: yes                       # yes or no
  connection: ssh                 # ssh or paramico
  gather_facts: yes               # yes or no
  vars:
   pkg: httpd
  tasks:
   - name: install httpd on CentOS7
     action: yum name='{{ pkg}}' state=installed
   - name: Start Apache
     action: service name='{{ pkg}}' state=started
