--- # My First YAML Playbook
- hosts: all
  user: ansible
  sudo: yes                       # yes or no
  connection: ssh                 # ssh or paramico
  gather_facts: yes               # yes or no
  tasks:
   - name: install httpd on CentOS7
     #action: yum name=httpd state=present
     command: touch /home/ansible/test.doc
     run_once: true
     delegate_to: ansiblehost-1 
     #notify: Start Apache
  handlers:
   - name: Start Apache
     service: name=httpd state=started
     delegate_to: ansiblehost-1
